---
title: "Literature Review"
format: html
bibliography: references.bib
---

## @blakers2021: A review of pumped hydro energy storage

[Dr. Blakers](https://researchers.anu.edu.au/researchers/blakers-aw) is a Professor of Engineering at Australian National University (ANU).

-   Big name in "high renewable energy futures" (solar photovoltaics & wind)
-   Schtick: wind + PV + pumped hydro energy storage + demand management + interconnection = all energy needs at less cost than current fossil fuels

### Paper summary

-   renaissance in pumped hydro storage = rapid increase in *variable* wind and solar
-   pumped hydro = 99% of global storage energy, 96% storage power
-   storage capacity (these are complimentary)
    -   pumped hydro = hours to weeks (and cheapest)
    -   batters = competitive for seconds to \~hour
-   BUT, 99% of opportunities are not near a river or water (need off-river hydro)
-   ANU 100% Renewable Energy Group created [global pumped hydro atlas](https://re100.eng.anu.edu.au/index.html)
    -   616,000 off-river sites; 23 million GW-hours = 100x more than needed for 100% electricity world
-   US = 35,000 sites, 1.4 million GWh = 300x more than needed to support solar/wind
-   All reservoirs are outside national parks or urban areas
    -   combined reservoir area is small (3 m\^2 per person per day)
    -   water requirement is small (3 liters per person per day); far less than coal

#### Hydro Technology

#### Best storage sites

#### Costs

#### Environmental impacts

-   impacts primary relate to flooding of land within reservoir
    -   on-river (open loop) impact are worse than off-river (closed loop)
    -   plus there are vastly more options available off-river, thus minimize risk
    -   other impacts: construction of roads, pipes/tunnels for conveying water, powerhouse, switchyard, high voltage transmission lines
-   How much storage capacity is needed?
    -   **rule of thumb = 1 d (24h) storage**, accommodates day-night cycle (batteries & PSH), about 27 GWh per million people
    -   @blakers2017 examined the amount of storage required to support a 100% renewable electricity system in Australia which derives 90% of its energy from variable wind and solar and 10% from existing hydro and bioenergy sources
    -   1 GW (storage) and 20 GWh (energy) per million people
    -   spillage of extra (\~ 5-25%) preferable to overbuilding storage [@blakers2017]
-   How much land is needed?
    -   land area required for off-river PHES systems to support high levels of variable solar and wind generation is relatively small and can be selected to minimise sensitive land
    -   per GWh, 12 ha for off-river PHES, head of 400m, 90% efficient, 85% usable water volume, 20 m average water depth = 3 m\^2 per person (queen size bed)
    -   For 27 GWh per 1 million people = 1 plant with 1 GW power and 3 km\^2 flooded area
    -   20x less land needed than for solar PVs
    -   then add floating PVs which can also reduce evaporation
-   How much water is needed?
    -   per GWh, 1 Gigalitre for off-rover PHES, head of 400m, 90% efficient
        -   doubling or halving head will double or half needed water
    -   For 27 GWh per 1 million people = 27 kl per person - NOT CONSUMED!
    -   water needed for initial fill and to replace evaporation is 3 l/person/day, which is about 20 s of a typical shower
    -   Evaporation suppressors can tip the balance in favour of rainfall in arid regions

#### Future energies & big picture

-   energy storage
    -   small home batteries good, but not for grid-scale
    -   utility scale (100 MW) batteries good for sub-second to hours
    -   pumped hydro for hours to weeks [@hunt2020; @nadeem2019]
-   demand management analogous to storage and very important
-   deep electrification is key to future, reduce emissions by ¾ [@blakers2019]
-   electricity demand needs to triple [@lu2021] to electrify transport (via electric vehicles), heating (via electric heat pumps and electric furnaces) and chemical synthesis
-   storage is not expensive
    -   cost to support 100% renewable grid in AUS is \$7 MWh−1 (\$18 with spillage)
    -   [current/expected solar/wind energy](https://reneweconomy.com.au/technology-leaps-driving-cost-of-solar-pv-electricity-in-australia-to-just-a30-mwh-42052/) = \$30--50 MWh−1 (2020) \$15--25 MWh−1 (2030)
-   Major economies (USA, EU, China, Japan) committed to 100% renewables by 2050s
    -   wind and solar will lead the way as cost of new-build way low
    -   per cap electricity consumption \~ 5-10 MWh/person/year
    -   eliminating fossil fuels = triple electricity production [@lu2021]
-   global human population at 10 billion by 2050; when developing counties reach advanced needs, world will need 200,000 TWh/year
-   assuming solar (60%), wind (30%), other (10%), need 81 TW solar, 17 TW wind
-   assuming 1 day rule of thumb, need 500 TWh (storage energy) and 20 TW (power)
    -   more than order of magnitude larger than now, but way less the available pool of off-rover pumped hydro resources (23,000 TWh)

### Main Takeaways

-   Off-river pumped hydro as a very large-scale low-cost and mature energy storage technology to support 100% renewable energy futures
-   Off river PHES is likely to have low environmental impact and low water consumption
    -   Little focus on actual ecological impacts - mostly large scale land/water use
    -   Effectively says no ecological impact on off-river, so long as placed in benign place

## @koohi-fayegh2020

-   pumped hydro provides storage from hours to weeks

## @hunt2020

-   pumped hydro provides storage from hours to weeks

## @nadeem2019

-   a range of storage technologies are under development

# References

::: {#refs}
:::
