---
title: "Meeting Notes"
format: html
bibliography: references.bib
---

## 03 Mar 2023

-   Bryan, Josh, Steve
-   Green Gen Storage Team
    -   Nicholas Sher (public works)
    -   Laura Johnson (permitting)
    -   Diana (stakeholders)

**PROJECT GOAL**: evaluate and mitigate the potential impacts and benefits of Mokelumne pumped hydro plant to the environment and stakeholders.

-   evaluate alternative operations and configurations
-   lit review on temp requirements of aquatic organisms
-   an innovate project at the water-energy-environment nexus

General project notes from Green Gen team:

-   energy for summer and fall - ***400 MW battery***
-   in process of permitting
-   through Pacific Gas and Electric (PG&E)
-   20 study plans - FERC approval
    -   special use authorization from the Forest Service (concern about recreation)
    -   then collect data (summer 2023)
-   Existing hydro already at Salt Springs
    -   this project may get them to halt those operations
-   River is stressed and dammed - 2 large dams
    -   **WOULD THIS PROJECT INCREASE STREAM TEMPERATURES BY MIXING WATERS?**
    -   fish and amphibians need cold water
-   already violating temperature rules - more stringent regs are in pipeline
    -   20 degrees C = max (from PNW regime)
    -   California water temps not good for regime (many think these need to change)
    -   intermittent snow pack by 2040s - bad for project regime
    -   climate change = bad, will this project make it worse?
-   Stantec is collecting data (lots of sampling in 2023)
    -   intake
    -   outflow and canal at Salt Springs
    -   reservoir profiles
    -   bathymetry maps
-   ONLY CARE ABOUT TEMPS AT LOWER (LARGER) RESERVOIR
-   10% of design is done - need to figure out bathymetry maps and where input goes
    -   could be variable intake - probably stationary
-   Tunneling could drain Cole creek
-   lake level change = inches to 6 feet, but variable
    -   vs current draw down (lowest in DEC) at lake via winter rights and energy needs
-   20 studies to do (7 biological)

What they need:

-   is the PNW standard appropriate?
-   CC impacts on watershed? 2030s, 2040s, etc
-   "Holistic outlook"
    -   impacts small, outcomes huge

    -   this project will help mitigate CC impacts, but people are concerned about local impacts like traffic, fishing, etc

    -   but we need energy storage
-   Floating PV on top, but people are not on board
-   Flume moralities - bears can drown...

## 11 May 2023

-   meet and greet with Hydroeco Lab group

    -   Hanna (MS) - stormwater ponds and eco services
    -   Eric (PhD) - Fish Lake groundwater flooding
    -   Will (PhD) - urban tree hydrology
    -   Arthur (PhD + DNR) - hydroecology of fens
    -   Aaron (phd)

-   Steve and I visited to discuss overall project plan and timeline for lit review

-   generally: learn, summarize, brief Steve

Action items

-   Font matter
    -   what is it (PSH)?
    -   knowledge gaps
    -   demand and trends
    -   learn the language
-   Use above to identify topics for inclusion in lit review (which become work chunks)
-   Impacts and Co-benefits
    -   operational changes to achieve low impacts and benefits
    -   entry / exist point
    -   floatovoltaics

## 14 July 2023

-   discussed my preliminary note taking / lit review
-   think about time scales of energy storage and when you need releases
-   keep in mind legal issues - wordsmith and don't prescribe

Action items

-   identify current impacts on Mokelumne River / Sac River
    -   already imparied system, not meeting TMDLs
    -   can lit review help fix stuff?!?
-   share Zotero lib with Steve
-   share link to html files from git hub
-   use Trello

## 01 Aug 2023

-   demand and generation trends for energy: hourly, daily, monthly, annually

    -   diurnal and seasonal cycles

-   what is service area?

-   daily water moving doesn't affect downstream

-   annually

-   will they be using

-   when does water demand occur? water right occur? can we delay water releases if its not needed in June per say? June is highed solar production - so reduce downstream releases in summer (with solar and pumped) then we dont need to do water releases for energy. only if that when farmers need water. or delay that till august because have enough energy in june, then befits for fisheries during highest stress periods.

-   are there benefits for doing this? then we have a discussion about changing it.

-   when is wind coming though? how much is solar vs wind?

-   is ther better habitat in downstream reaches of salt springs or mokumnle? which stream needs more? you could move water to accommodate if one is very good habitat, if only it had this extrra thing.

-   how much electricity is normally proiduced on the system by saving water and releaseing later VERSUS batter time. if we saved all water and released in fall (is that a little or small amount versus capapcity)

    -   battery storage needed for 1 day is fairly large compared to overall storager
    -   if you used all water, how long would it last

-   contact GreenGen - let them know we are working on this.

-   reduce impacts of traditional hydropower (esp. hydropeaking)?

    -   shift water releases later in the season with conjuctive management between pumped storage hydropower and traditional hydropower
    -   PSH and traditional hydropower might be able to work together to reduce the need for hydropeaking in traditional hydropower (which is bad)
        -   affects water exahcnge with surroundings
        -   etc.
        -   HSP could smooth some of that out

Action items

1.  typical diurnal/seasonal/annual pumped hydro schedule
2.  typical diurnal/seasonal/annual conventional hydro schedule
3.  typical hydrographs for study area

## 20 Aug 2023

Met Brenda Pracheil at AFS 2023 in Grand Rapids. She is a Fisheries Biologist with the Pacific Northwest National Lab (but stationed in Knoxville TN at ORNL) and is working on PSH generally, specifically with off-channel PSH.

Brenda told me about [PNNL's Energy Storage Webinar Series](https://www.pnnl.gov/events/energy-storage-pnnl-series), and they just did one on PSH.

Mentioned the HydroWires 2020 report on comparing the environmental impacts of open- and closed-loop PSH [@saulsbury2020], and one on the FERC licensing process [@levine2021].

The report her group are doing this year, in comparison to the 2020 report, will be more quantitative and look more like an EIS document. Looking to write papers from this report and collaborate.

Brenda's talk at AFS was "Energy flexibility-environment tradeoff toolkit for hydropower environmental and operational flows.

Action Items:

-   follow up with Brenda in \~ 1-2 month
